### ISSUE TITLE
Headphones keeps restarting

### ISSUE THREAD

**Issue by dvandonkelaar** [linuxserver/docker-headphones#21]
Synology Docker, DSM 6.1.1-1501 update 2
Latest version of linuxserver/headphones

Environment:
TZ = Europe/Amsterdam
PGID = 0
PUID = 0

When adding artists and searching for information, Headphones restarts. No messages in the logs contain an error or a fault.

**Comment by Fish2** [comment]
I am getting the same cant get any info on it

**Comment by j0nnymoe** [comment]
@dvandonkelaar try not running it as root, we recommend you run our containers as normal users.

**Comment by dvandonkelaar** [comment]
Changing PUID to a normal user and PGID to 100 (Users) and 101 (Administrators) does not resolve the problem.

**Comment by Fish2** [comment]
im using mine as 1000

**Comment by pbertra** [comment]
Same issue but the seems to occur when I connect to the server on the web interface. If no client is connected, the server keeps running.
I am using a specific user, Docker version 17.05.0-ce, build 89658be

**Comment by chrisarrison** [comment]
Same here

I have seen this message in the logs:

Can't connect to the database: 'NoneType' object has no attribute '__getitem__'

not sure if it's relevant. Does anyone else see this?

**Comment by chrisarrison** [comment]
is anyone still experiencing this? I have added some artists ok, but with others the server app just restarts constantly.

**Comment by pbertra** [comment]
Yes, it keeps happening, even with the latest version and correct puid/pgid

**Comment by volumen1** [comment]
I'm also having this issue

**Comment by francesco995** [comment]
change /config to /data and the error is fixed

**Comment by Fish2** [comment]
what in the docker line or in the headphones config ?

**Comment by francesco995** [comment]
problem is that as soon as i go to an artist page, the container crash and restarts. if i don't map config or map it to /data, it works fine but obviously don't keep configuration on restart

**Comment by tpiggott** [comment]
This appears to be the same as issue #16. Any action on the Artist Information page is causing a GET request for artist icon art that is causing Python to segfault.

I'm still seeing it as of today, with the latest image. Has there been any movement on this?

**Comment by Stealthii** [comment]
I believe this is caused by the library errors as part of running under Python 3.x, as tracked by #30.

**Comment by sparklyballs** [comment]
@Stealthii this image is based on python 2.7
